### ISSUE TITLE
Diseño del Proyecto

### ISSUE THREAD

**Issue by fabdelgado** [fabdelgado/Atraco-Casa-de-Papel#1]
Tarea para diseñar el proyecto

**Comment by mcm0151** [comment]
Empezamos a diseñar el proyecto.

**Comment by fabdelgado** [comment]
Adjunto la primera versión del documento de diseño
[diseñov1.pdf](https://github.com/fabdelgado/Atraco-Casa-de-Papel/files/3843491/disenov1.pdf)

**Comment by fabdelgado** [comment]
Se entrega el documento final
[diseño_final.pdf](https://github.com/fabdelgado/Atraco-Casa-de-Papel/files/3843502/diseno_final.pdf)

**Comment by mcm0151** [comment]
Se da por finalizado el diseño del proyecto.
