### ISSUE TITLE
Reunir el equipo

### ISSUE THREAD

**Issue by mcm0151** [fabdelgado/Atraco-Casa-de-Papel#2]
Esta tarea pretende establecer los criterios para reunir un grupo de personas.

**Comment by fabdelgado** [comment]
Hemos reunido al equipo: 
Silene Oliveira (Tokio)
Sergio Marquina (El Profesor)
Agustín Ramos (Moscú)
Andrés de Fonollosa (Berlín)
Ágata Jiménez (Naerobi)
Aníbal Cortés (Río)
Ricardo Ramos (Denver)
Mónica Gaztambide (Estocolmo)

**Comment by fabdelgado** [comment]
Se cierra el issue ya que se cuenta con el equipo.
